matrix:
  include:
    - language: python
      python: "3.5"
      install:
        - pip install -r requirements.txt
      script:
        - find . -iname "*.py" | xargs python3 -m pytest
        - find rows* -iname "*.py" | xargs python3 -m pylint
    - language: cpp
      dist: trusty
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake
            - build-essential
            - git
            - pkg-config
            - libbz2-dev
            - libxml2-dev
            - libzip-dev
            - libboost-all-dev
            - lua5.2
            - liblua5.2-dev
            - libtbb-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      script:
        - mkdir -p build && cd build && cmake .. && make -j 2

notifications:
  email: false