language: python
python:
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  - python3 -m pytest */**.py
  - python3 -m pylint */**.py --disable=too-few-public-methods --disable=missing-docstring --disable=fixme

notifications:
  email: false