language: python
python:
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  - find . -iname "*.py" | xargs python3 -m pytest
  - find . -iname "*.py" | xargs python3 -m pylint

notifications:
  email: false